name: travel_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1  # Versi terbaru
  cupertino_icons: ^1.0.8  # Versi terbaru
  ionicons: ^0.2.2  # Versi terbaru

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/places/
    - assets/icons/
    - assets/